export interface information {
  id: number;
  fName: string;
  range: number;
  range_h: number;
  frequency_lt: number;
  frequency_nfft_r: number;
  frequency_nfft_b: number;
  frequency_lsp_r: number;
  frequency_lsp_b: number;
}

const dataset: information[] = [
  {
    id: 1,
    fName: 'KHLONG MARUI',
    range: 4719,
    range_h: 2589,
    frequency_lt: 0,
    frequency_nfft_r: 0,
    frequency_nfft_b: 0,
    frequency_lsp_r: 0,
    frequency_lsp_b: 0,
  },
  {
    id: 2,
    fName: 'MAE CHAN',
    range: 5070,
    range_h: 2829,
    frequency_lt: 0,
    frequency_nfft_r: 9,
    frequency_nfft_b: 4,
    frequency_lsp_r: 9.4,
    frequency_lsp_b: 5.4,
  },
  {
    id: 3,
    fName: 'MAE HONG SON',
    range: 4628,
    range_h: 2842,
    frequency_lt: 7,
    frequency_nfft_r: 7,
    frequency_nfft_b: 4,
    frequency_lsp_r: 6.6,
    frequency_lsp_b: 5.2,
  },
  {
    id: 4,
    fName: 'MAE ING',
    range: 4958,
    range_h: 2557,
    frequency_lt: 0,
    frequency_nfft_r: 0,
    frequency_nfft_b: 0,
    frequency_lsp_r: 0,
    frequency_lsp_b: 0,
  },
  {
    id: 5,
    fName: 'MOEI',
    range: 5013,
    range_h: 2911,
    frequency_lt: 0,
    frequency_nfft_r: 6,
    frequency_nfft_b: 3,
    frequency_lsp_r: 5.8,
    frequency_lsp_b: 3.4,
  },
  {
    id: 6,
    fName: 'MAE THA',
    range: 6266,
    range_h: 2868,
    frequency_lt: 0,
    frequency_nfft_r: 7,
    frequency_nfft_b: 6,
    frequency_lsp_r: 6.2,
    frequency_lsp_b: 5.98,
  },
  {
    id: 7,
    fName: 'THOEN',
    range: 5145,
    range_h: 2832,
    frequency_lt: 0,
    frequency_nfft_r: 7,
    frequency_nfft_b: 4,
    frequency_lsp_r: 5.8,
    frequency_lsp_b: 3.4,
  },
  {
    id: 8,
    fName: 'PHETCHABUN',
    range: 2814,
    range_h: 2814,
    frequency_lt: 0,
    frequency_nfft_r: 0,
    frequency_nfft_b: 0,
    frequency_lsp_r: 0,
    frequency_lsp_b: 0,
  },
  {
    id: 9,
    fName: 'PUA',
    range: 3736,
    range_h: 2690,
    frequency_lt: 0,
    frequency_nfft_r: 0,
    frequency_nfft_b: 0,
    frequency_lsp_r: 0,
    frequency_lsp_b: 0,
  },
  {
    id: 10,
    fName: 'PHA YAO',
    range: 5510,
    range_h: 2793,
    frequency_lt: 0,
    frequency_nfft_r: 6,
    frequency_nfft_b: 7,
    frequency_lsp_r: 7.4,
    frequency_lsp_b: 7,
  },
  {
    id: 11,
    fName: 'RANONG',
    range: 4523,
    range_h: 2794,
    frequency_lt: 0,
    frequency_nfft_r: 0,
    frequency_nfft_b: 0,
    frequency_lsp_r: 0,
    frequency_lsp_b: 0,
  },
  {
    id: 12,
    fName: 'SI SAWAT',
    range: 4593,
    range_h: 2585,
    frequency_lt: 0,
    frequency_nfft_r: 6,
    frequency_nfft_b: 4,
    frequency_lsp_r: 6.2,
    frequency_lsp_b: 5,
  },
  {
    id: 13,
    fName: 'THREE PAGODA',
    range: 4432,
    range_h: 2383,
    frequency_lt: 0,
    frequency_nfft_r: 0,
    frequency_nfft_b: 0,
    frequency_lsp_r: 0,
    frequency_lsp_b: 0,
  },
  {
    id: 14,
    fName: 'UTTARADIT',
    range: 3254,
    range_h: 2127,
    frequency_lt: 0,
    frequency_nfft_r: 0,
    frequency_nfft_b: 0,
    frequency_lsp_r: 0,
    frequency_lsp_b: 0,
  },
  {
    id: 15,
    fName: 'WIANG HAENG',
    range: 5022,
    range_h: 2831,
    frequency_lt: 0,
    frequency_nfft_r: 0,
    frequency_nfft_b: 0,
    frequency_lsp_r: 0,
    frequency_lsp_b: 0,
  },
  {
    id: 16,
    fName: 'MAE LAO',
    range: 4930,
    range_h: 2867,
    frequency_lt: 0,
    frequency_nfft_r: 6,
    frequency_nfft_b: 4,
    frequency_lsp_r: 2.2,
    frequency_lsp_b: 3.62,
  },
];

export default dataset;
